spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_workshops
    driver-class-name: org.postgresql.Driver
    username: app_data
    password: p@ssw0rd
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: app_data
    password: p@ssw0rd
    baseline-description: "init"
    baseline-version: 0