spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_workshops
    driver-class-name: org.postgresql.Driver
    username: app_data
    password: p@ssw0rd
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect